theme: jekyll-theme-minimal
title: Model selection for high dimensional data with applications toward genetics
site.description: test editing here
annoncement.url: http:://
annoncement.page: homepage for annoncement
